### ISSUE TITLE
client side bug

### ISSUE THREAD

**Issue by lifeiscontent** [invisible-college/braidjs#1]
I noticed when someone was updating the content on the https://braid.news/ site an hour or so ago that the site was jumping around. I'm guessing theres a `React.memo` that is missing somewhere because currently each node in the DOM seems to be updating rather than diffing changes.

cool idea though, excited to see what you guys do with it.

**Comment by toomim** [comment]
Ha! That was me editing the "implementations" portion of the page.

This page is actually generated from markdown. With each keystroke, it re-renders the markdown into HTML, and then dangerouslySetsHTML.

This markdown is, in turn, running within a React component. (There are lots of turtles here.) But since it's not generated virtual dom, there isn't any diffing.

This full-page-re-rendering only happens when we edit the page's source code, though. So it's not too bad in practice.

Thanks for checking out Braid, and leaving this note! Can I ask what interests you in the project?

**Comment by lifeiscontent** [comment]
I helped build a visual compiler which had a similar messaging system. I find this kind of technology to be interesting. I think this kind of system plus a few other layers might become the future of programming

**Comment by toomim** [comment]
Awesome! I do too. :)

Can you link or explain a little about the visual compiler's messaging system? I'm curious.

**Comment by lifeiscontent** [comment]
We used browser-fs and isomorphic git, each message was a commit so it was version controlled. Similar concepts to this, but obviously a bit more cycles involved.

**Comment by toomim** [comment]
Oh, wow, that's very cool! It sounds like a similar architecture that @brynbellomy used when building http://axon.science/. He found that git worked great for large-grain versions, but had difficulties when trying to synchronize the JSON state of a trello board in git, when multiple people might move cards in the trello board, and thus change the underlying json.

I'm also glad to discover this isomorphic-git project, because the first synchronizer that @dglittle 
and I built was also like a mini-git, in javascript— we re-implemented git's recursive 3-way merge algorithm, and repurposed it for collaborative editing. It actually worked quite well!  https://github.com/invisible-college/universal-sync/blob/gh-pages/diffsync.js.

I also think Sparkleshare is cool, which uses an *actual* git instance to support collaborative editing: https://www.sparkleshare.org/

I'm quite excited about the possibility to do all these things much more efficiently, and to embed them directly into HTTP, so that everything just works like this by default.

**Comment by lifeiscontent** [comment]
@toomim are you still working on this? What're you up too? :)

**Comment by toomim** [comment]
Yes! But development has been happening in a different repo: over at [`braid-work/toomim-braidjs`](https://github.com/braid-work/toomim-braidjs). You'll see lots of commits there over the last month.

We should have a beta release at the end of January. This will be a low-level synchronizer, running over http, that works in a web browser and nodejs server.

We can then build demos, and higher-level features on this, leading up to the IETF meeting in March.

I'll also be posting a status report to the [braid-http mailing list](https://groups.google.com/forum/#!forum/braid-http) very soon.

**Comment by lifeiscontent** [comment]
@toomim nice! I'd be down to migrate code to TypeScript if that seems like something you'd want to add.

**Comment by toomim** [comment]
Oh, that's a very nice offer. :) I don't think we need Typescript, though.
